// Explaining different types of impairments and their classifications 

export default function Impairments() {
  const impairmentTypes = [
    {
      title: "Physical Impairments",
      description: "Affects body movements and muscle control",
      categories: [
        {
          name: "Impaired Muscle Power",
          description: "Reduced force generated by muscles or muscle groups",
          examples: ["Spinal cord injury", "Muscular dystrophy", "Spina bifida"]
        },
        {
          name: "Impaired Range of Movement",
          description: "Reduced range of movement in one or more joints",
          examples: ["Arthrogryposis", "Joint contractures", "Trauma"]
        },
        {
          name: "Limb Deficiency",
          description: "Total or partial absence of bones or joints",
          examples: ["Amputation", "Dysmelia", "Congenital limb deficiency"]
        }
      ]
    },
    {
      title: "Visual Impairments",
      description: "Affects vision acuity and/or field of vision",
      categories: [
        {
          name: "B1",
          description: "No light perception up to light perception",
          examples: ["Total blindness", "Severe visual impairment"]
        },
        {
          name: "B2",
          description: "Ability to recognize shapes up to visual acuity of 2/60",
          examples: ["Severe visual impairment"]
        },
        {
          name: "B3",
          description: "Visual acuity from 2/60 to 6/60",
          examples: ["Moderate visual impairment"]
        }
      ]
    },
    {
      title: "Intellectual Impairments",
      description: "Affects cognitive functions and adaptive behavior",
      categories: [
        {
          name: "II1",
          description: "IQ of 75 or lower and limitations in adaptive behavior",
          examples: ["Intellectual disability affecting learning and execution"]
        }
      ]
    }
  ];

  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6">Understanding Paralympic Impairments</h1>
      
      <div className="space-y-8">
        {impairmentTypes.map((type, index) => (
          <section key={index} className="bg-white rounded-lg shadow-md p-6">
            <h2 className="text-2xl font-semibold mb-4">{type.title}</h2>
            <p className="text-gray-700 mb-6">{type.description}</p>
            
            <div className="grid gap-4 md:grid-cols-2">
              {type.categories.map((category, i) => (
                <div key={i} className="bg-gray-50 p-4 rounded-lg">
                  <h3 className="font-semibold mb-2">{category.name}</h3>
                  <p className="text-gray-700 mb-3">{category.description}</p>
                  <div className="bg-white p-3 rounded">
                    <p className="text-sm font-medium text-gray-600 mb-2">Examples:</p>
                    <ul className="list-disc list-inside text-sm text-gray-700">
                      {category.examples.map((example, j) => (
                        <li key={j}>{example}</li>
                      ))}
                    </ul>
                  </div>
                </div>
              ))}
            </div>
          </section>
        ))}

        <section className="bg-blue-50 p-6 rounded-lg">
          <h2 className="text-xl font-semibold mb-4">Important Notes</h2>
          <ul className="space-y-2 text-gray-700">
            <li>• Classifications are sport-specific and may vary between sports</li>
            <li>• Athletes may be classified differently in different sports</li>
            <li>• Regular reviews ensure classifications remain appropriate</li>
            <li>• Classification is based on functional ability, not medical diagnosis</li>
          </ul>
        </section>
      </div>
    </div>
  );
} 